version: "3.7"

services:
  web:
    image: nginx
    deploy:
      replicas: 12
      resources:
        limits:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "8000:80"
    networks:
    - webserver

networks:
  webserver:
