version: "3.7"

services:
  web:
    image: nginx
    deploy:
      replicas: 16
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
    - "8030:80"
    networks:
    - webserver

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8040:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 4
      placement:
        constraints: [node.role == manager]
    networks:
    - webserver

networks:
  webserver:
