version: "3.7"

services:
  database:
    image: mysql:5.7
    volumes:
    - /mnt/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
    - database
    image: wordpress:latest
    ports:
    - "8020:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_PASSWORD: wordpress
